application: monashclubs
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /assets/js
  static_dir: assets/js
  
- url: /assets/css
  static_dir: assets/css
  
- url: /assets/img
  static_dir: assets/img
  
- url: /.*
  script: trackingapp.app
  
  